#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = SimpleSmartPointerInheritanceExample

PATHS *= \
    .

SOURCES += main.cpp
CONFIG += c++14
DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS
